### PR TITLE
Feature: auto-fix for specific linters

### LINKED ISSUE #426: Suggestion: option to enable auto fix for specific linters
Some linters do not support auto fix, maybe this will be a fix

Something like:
black_auto_fix: true

### PR DESCRIPTION
**Pull request by phamelink**
Fixes #426.

With @BastienFaivre, we added a feature to enable auto fix for specific linters requested in this issue #426. 

We made several attempts at this, starting with using `<linter>_auto_fix` to only commit and push certain file extensions found in the input for each linter. When we realised that this wasn't very efficient as there could be edge cases where this would cause problems if some linters have common file extensions, we tried another way, where we would restore the branch at the start of every linter iteration. Finally, we realised that this actually wasn't necessary, as we could directly prevent a linter from auto-fixing by using `autoFix && linterAutoFix` as the `fix` parameter in a linter's `lint` function.

We also made sure to add documentation about this feature in the README and made an example where this could be used (typically for linters like flake8 which do not support auto-fixing).

We tested these changes on this [repo](https://github.com/phamelink/test-action-repo), and it seems to be working as expected.

### CODE REVIEW

File: dist/index.js [hunk 1]
```diff
@@ -4372,6 +4372,7 @@ async function runAction() {
 			const lintDirRel = core.getInput(`${linterId}_dir`) || ".";
 			const prefix = core.getInput(`${linterId}_command_prefix`);
 			const lintDirAbs = join(context.workspace, lintDirRel);
+			const linterAutoFix = core.getInput(`${linterId}_auto_fix`) === "true";
```
Comment (ocean90) [inline dist/index.js:4375]:
```suggestion
			const linterAutoFix = false === autoFix 
 ? false : core.getInput(`${linterId}_auto_fix`) === "true";
```

Can we set `linterAutoFix` false by default if `autoFix` is set to false? This would allow to replace the `autoFix && linterAutoFix` checks below with just `linterAutoFix`.

File: action.yml [hunk 2]
```diff
@@ -331,6 +379,10 @@ inputs:
     description: Shell command to prepend to the linter command
     required: false
     default: ""
+  erblint_auto_fix:
+    description: Whether this linter should try to fix code style issues automatically. If set to `true`, it will only work if "auto_fix" is set to `true` as well
+    required: false
+    default: "true"
```
Comment (ocean90) [inline action.yml:385]:
```suggestion
    default: "false"
```

Would it make sense to set the default to false if we know a linter doesn't support auto-fixing?

Comment (Daniel-Atanasov) [reply action.yml:385]: That would fix these warnings with `auto_fix: true`:
image

Comment (phamelink) [reply action.yml]: Hi @ocean90, thanks for the feedback. You're right that does make more sense! We made these changes in our last commit

File: README.md [hunk 3]
```diff
@@ -305,6 +349,7 @@ jobs:
 - **`[linter]_dir`**: Directory where the linting command should be run. Example: `eslint_dir: server/` if ESLint is installed in the `server` subdirectory. Default: Repository root
 - **`[linter]_extensions`:** Extensions of files to check with the linter. Example: `eslint_extensions: js,ts` to lint JavaScript and TypeScript files with ESLint. Default: Varies by linter, see [`action.yml`](./action.yml)
 - **`[linter]_command_prefix`:** Command prefix to be run before the linter command. Default: `""`.
+- **`[linter]_auto_fix`:** Whether the linter should try to fix code style issues automatically. This option is useful to commit and push changes only for specific linters and not all of them when `auto_fix` option is set. Default: `true`.
```
Comment (ocean90) [inline README.md:352]:
```suggestion
- **`[linter]_auto_fix`:** Whether the linter should try to fix code style issues automatically. This option is useful to commit and push changes only for specific linters and not all of them when `auto_fix` option is set. Default: `true` if linter supports auto-fixing, `false` if not.
```

**Review by ocean90 — CHANGES_REQUESTED** [review]
This is looking good, just one minor doc change.

**Review by ocean90 — APPROVED** [review]

**Comment by ocean90** [comment]
Nice job, thank you!
